export default {
  IllustAircraft: require('@images/illustrations/aircraft.png'),
  IllustCoder: require('@images/illustrations/computer-and-man.png'),
  IllustTeam: require('@images/illustrations/creative-team.png'),
  IllustRemoteTeam: require('@images/illustrations/remote-team.png'),
  IllustSettings: require('@images/illustrations/settings.png'),
  IllustNotification: require('@images/illustrations/notifications.png'),
  logoWhite: require('@images/logos/logoWhite.png'),
  logoFaceID: require('@images/logos/face-id.png'),
  logoTouchID: require('@images/logos/touch-id.png'),
  IllustNoSaved: require('@images/illustrations/into-the-night.png'),
  IllustBackground: require('@images/illustrations/landscape.jpg'),
  coinPlus : require('@images/dfians/coinPlus.png'),
  dfiansLogo : require('@images/dfians/dfiansLogo.png'),
  reload : require('@images/dfians/reload.png'),
  backArrow : require('@images/dfians/backArrow.png'),
  rightArrow : require('@images/dfians/rightArrow.png'),
  ADA : require('@images/dfians/ADA.png'),
  backWardImg : require('@images/dfians/backWardImg.png'),
  bottomArrow : require('@images/dfians/bottomArrow.png'),
  BTC : require('@images/dfians/btcLogo.png'),
  bulligoBanner : require('@images/dfians/bulligoBanner.png'),
  button : require('@images/dfians/button.png'),
  close : require('@images/dfians/close.png'),
  depositGoodBack : require('@images/dfians/depositGoodBack.png'),
  DFiansFavicon : require('@images/dfians/DFiansFavicon.png'),
  DFiansLogoGray : require('@images/dfians/DFiansLogo-gray.png'),
  dfiansLogo : require('@images/dfians/dfiansLogo.png'),
  DFSCLogo : require('@images/dfians/DFSCLogo.png'),
  EOS : require('@images/dfians/EOS.png'),
  ETH : require('@images/dfians/ETH.png'),
  // favcicon : require('@images/dfians/favcicon.ico'),
  ICOgraph : require('@images/dfians/ICOgraph.png'),
  icon_3 : require('@images/dfians/icon_3.png'),
  loading : require('@images/dfians/loading.png'),
  m_my : require('@images/dfians/m-my.png'),
  m_wallet : require('@images/dfians/m-wallet.png'),
  m_goods : require('@images/dfians/m-goods.png'),
  m_menu : require('@images/dfians/m-menu.png'),
  menu : require('@images/dfians/menu.png'),
  notification : require('@images/dfians/notification.png'), 
  my_inquiry_list_none : require('@images/dfians/my-inquiry-list-none.png'),
  my_wallet_icon : require('@images/dfians/my-wallet-icon.png'),
  purchase : require('@images/dfians/purchase.png'),
  pwArrow : require('@images/dfians/pwArrow.png'),
  pwSequence_1 : require('@images/dfians/pwSequence-1.png'),
  pwSequence_2 : require('@images/dfians/pwSequence-2.png'),
  pwSequence_3 : require('@images/dfians/pwSequence-3.png'),
  pwWeb : require('@images/dfians/pwWeb.png'),
  QRCode : require('@images/dfians/QRCode.png'),
  receive : require('@images/dfians/receive.png'),
  m_wallet : require('@images/dfians/m-wallet.png'),
  reminder : require('@images/dfians/reminder.png'),
  searchBox : require('@images/dfians/searchBox.png'),
  send : require('@images/dfians/send.png'),
  sns_naver : require('@images/dfians/sns_naver.png'),
  sns_kakao : require('@images/dfians/sns-kakao.png'),
  swap : require('@images/dfians/swap.png'),
  XRP : require('@images/dfians/XRP.png'),
  // Vector : require('@images/dfians/Vector.png'),
  clarity_copy_line : require('@images/dfians/clarity_copy-line.png'),
  StarOn : require('@images/dfians/Star_3.png'),
  StarOff : require('@images/dfians/Star_2.png'),
  complet : require('@images/dfians/complet.png'),
  wave : require('@images/dfians/wave.png'),
  Logo : require('@images/dfians/Logo.png'),
  modalClose : require('@images/dfians/modalClose.png'),
  signUp : require('@images/dfians/signUp.png'),
  ArrowDown : require('@images/dfians/ArrowDown.png'),
  ArrowUp : require('@images/dfians/ArrowUp.png'),
  check : require('@images/dfians/check.png'),
  onCheck : require('@images/dfians/onCheck.png'),
  lock : require('@images/dfians/lock.png'),
  fingerprint : require('@images/dfians/fingerprint.png'),
  googleOtpLogo: require('@images/dfians/Google_OTP_Logo.png'),
  buttonOff: require('@images/dfians/buttonOff.png'),
  buttonOn: require('@images/dfians/buttonOn.png'),
  googlePlay: require('@images/dfians/googleplay_subicon.png'),
  apple: require('@images/dfians/Apple_subicon.png'),
  DFSC: require('@images/dfians/DFSC.png'),
  DFSD: require('@images/dfians/DFSD.png'),
  complete: require('@images/dfians/complete.png')

};
